package com.relay.application.assistant;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.relay.application.brief.BriefService;
import com.relay.application.json.Json;
import com.relay.application.port.ConnectionRepository;
import com.relay.application.port.LlmClient;
import com.relay.application.port.LlmPurpose;
import com.relay.application.port.LlmRequest;
import com.relay.application.port.LlmResponse;
import com.relay.application.port.Tool;
import com.relay.application.port.ToolRegistry;
import com.relay.application.port.ToolResult;
import com.relay.domain.Connection;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * {@code POST /api/ask} — "kargolarım gelmiş mi?" answered from the user's own mailbox.
 *
 * <p>Three steps, and each one is visible in the response:
 * <ol>
 *   <li>{@link MailQueryTranslator} turns the question into a Gmail query. The query is
 *       returned to the caller, always — the user has to be able to see what was searched.</li>
 *   <li>{@code gmail.search} runs it. READ only: this endpoint has no path to a write tool,
 *       and it never starts a run.</li>
 *   <li>The model writes a Turkish answer <em>from those mails only</em>, and the mails it
 *       was given come back as {@code sources}.</li>
 * </ol>
 *
 * <p>The rule that matters: <b>no results means no answer.</b> With an empty result set the
 * model is never called at all — the endpoint says it found nothing and repeats the query it
 * used. A confident paragraph about a package that was never mentioned in any mail is the
 * single worst thing a mailbox assistant can do.
 *
 * <p>The same applies when the model is on the stub: an assistant answer is only generated by
 * a real model. Degraded, the endpoint lists what it found and says so, which is true.
 */
public class AskService {

    private static final Logger LOG = System.getLogger(AskService.class.getName());

    public static final String SEARCH_TOOL = "gmail.search";

    /** Wire status for the caller: what kind of answer this is. */
    public static final String OK = "ok";
    public static final String EMPTY = "empty";
    public static final String UNAVAILABLE = "unavailable";
    public static final String ERROR = "error";

    /** How the {@code answer} text was produced — {@code llm} or a plain list of what was found. */
    public static final String ANSWER_LLM = "llm";
    public static final String ANSWER_LISTING = "listing";
    public static final String ANSWER_NONE = "none";

    private static final int MAX_QUESTION_LENGTH = 500;
    private static final int MAX_RESULTS = 15;
    private static final int MAX_SOURCES = 8;
    private static final int MAX_ANSWER_LENGTH = 1200;
    private static final int MAX_SNIPPET_LENGTH = 220;

    private static final Pattern CITATION = Pattern.compile("\\[(\\d{1,2})]");

    private final ToolRegistry tools;
    private final ConnectionRepository connections;
    private final MailQueryTranslator translator;
    private final LlmClient llm;

    public AskService(ToolRegistry tools, ConnectionRepository connections,
                      MailQueryTranslator translator, LlmClient llm) {
        this.tools = tools;
        this.connections = connections;
        this.translator = translator;
        this.llm = llm;
    }

    /** One mail the answer is allowed to lean on. Exactly what the wire shows. */
    public record Source(String id, String subject, String from, String at, String url) {

        public Map<String, Object> view() {
            Map<String, Object> map = new LinkedHashMap<>();
            map.put("id", id);
            map.put("subject", subject);
            map.put("from", from);
            map.put("at", at);
            map.put("url", url);
            return map;
        }
    }

    // ---- entry point ------------------------------------------------------

    public Map<String, Object> ask(String question) {
        String cleaned = question == null ? "" : question.trim();
        if (cleaned.isEmpty()) {
            throw new IllegalArgumentException("soru boş olamaz");
        }
        if (cleaned.length() > MAX_QUESTION_LENGTH) {
            throw new IllegalArgumentException("soru çok uzun — en fazla "
                    + MAX_QUESTION_LENGTH + " karakter");
        }

        MailQueryTranslator.Translation translation = translator.translate(cleaned);
        long tokens = translation.tokens();
        double cost = translation.costUsd();

        Tool tool = tools.find(SEARCH_TOOL).orElse(null);
        if (tool == null) {
            return body(cleaned, translation, UNAVAILABLE, ANSWER_NONE,
                    "Gmail araması bu kurulumda kayıtlı değil, bu yüzden postana bakamadım.",
                    List.of(), tokens, cost, null);
        }

        Connection connection = connections.findByProvider(tool.provider()).orElse(null);
        ObjectNode params = Json.object();
        params.put("query", translation.query());
        params.put("maxResults", MAX_RESULTS);

        ToolResult result = tool.execute(params, connection);
        if (!result.ok()) {
            // The provider's own message can carry a token; it is translated, never forwarded.
            LOG.log(Level.WARNING, "ask: gmail.search failed: {0}", result.error());
            return body(cleaned, translation, ERROR, ANSWER_NONE,
                    BriefService.failureReason("Gmail", result.error()),
                    List.of(), tokens, cost, result.mode());
        }
        if ("replay (no connection)".equals(result.mode())) {
            // Live, without a Google connection: say so instead of passing demo fixtures
            // off as the user's mailbox.
            return body(cleaned, translation, UNAVAILABLE, ANSWER_NONE,
                    "Gmail bağlı değil — Ayarlar'dan bağlayınca bu soruyu yanıtlayabilirim. "
                            + "Sorguyu şöyle çevirmiştim: " + translation.query(),
                    List.of(), tokens, cost, result.mode());
        }

        List<Source> sources = sources(result.data());
        if (sources.isEmpty()) {
            // Nothing found: state that, name the query, and do not call the model.
            return body(cleaned, translation, EMPTY, ANSWER_NONE,
                    "Bu sorguyla eşleşen mail bulamadım: " + translation.query()
                            + ". Sorunu biraz farklı sorarsan tekrar deneyebilirim.",
                    List.of(), tokens, cost, result.mode());
        }

        String answer = null;
        String answerSource = ANSWER_LISTING;
        if (!llm.degraded()) {
            try {
                LlmResponse response = llm.complete(answerRequest(cleaned, translation.query(),
                        result.data(), sources));
                tokens += response.totalTokens();
                cost += response.costUsd();
                // The router can drop to the stub *inside* the call — the keys ran out
                // between the degraded() check and the request. Live, that put the stub's
                // "Sonuç bulunamadı: <the entire prompt>" on screen as the answer, internal
                // instructions and all. A stub response is not an answer, whatever the
                // client said about itself a moment earlier.
                answer = response.fallback() ? null : sanitizeAnswer(response.content(), sources.size());
                if (answer != null) {
                    answerSource = ANSWER_LLM;
                }
            } catch (RuntimeException e) {
                LOG.log(Level.WARNING, "ask: answer call failed ({0}) — listing the hits instead",
                        e.getClass().getSimpleName());
            }
        }
        if (answer == null) {
            answer = listing(sources);
        }
        return body(cleaned, translation, OK, answerSource, answer, sources, tokens, cost, result.mode());
    }

    // ---- results ----------------------------------------------------------

    private static List<Source> sources(JsonNode data) {
        List<Source> out = new ArrayList<>();
        for (JsonNode message : data.path("messages")) {
            String id = message.path("id").asText("");
            if (id.isBlank()) {
                continue;
            }
            out.add(new Source(id,
                    blankTo(message.path("subject").asText(""), "(konusuz)"),
                    message.path("from").asText(""),
                    message.path("receivedAt").asText(""),
                    "https://mail.google.com/mail/u/0/#all/" + id));
            if (out.size() >= MAX_SOURCES) {
                break;
            }
        }
        return out;
    }

    /** What the endpoint says when no model may speak: the hits, in order, and nothing else. */
    private static String listing(List<Source> sources) {
        StringBuilder sb = new StringBuilder();
        sb.append(sources.size() == 1 ? "1 mail buldum:" : sources.size() + " mail buldum:");
        for (int i = 0; i < sources.size(); i++) {
            Source source = sources.get(i);
            sb.append("\n[").append(i + 1).append("] ").append(source.subject());
            String from = person(source.from());
            if (!from.isBlank()) {
                sb.append(" — ").append(from);
            }
            String day = day(source.at());
            if (!day.isBlank()) {
                sb.append(" (").append(day).append(')');
            }
        }
        return sb.toString();
    }

    // ---- answer -----------------------------------------------------------

    private LlmRequest answerRequest(String question, String query, JsonNode data, List<Source> sources) {
        StringBuilder user = new StringBuilder();
        user.append("SORU: ").append(question).append('\n');
        user.append("ÇALIŞTIRILAN GMAIL SORGUSU: ").append(query).append("\n\n");
        user.append("BULUNAN MAİLLER:\n");

        List<JsonNode> messages = new ArrayList<>();
        data.path("messages").forEach(messages::add);
        for (int i = 0; i < sources.size(); i++) {
            Source source = sources.get(i);
            user.append('[').append(i + 1).append("] from=").append(source.from())
                    .append(" | subject=").append(source.subject())
                    .append(" | at=").append(source.at())
                    .append(" | snippet=").append(snippet(messages, source.id()))
                    .append('\n');
        }
        user.append("\nBu maillere dayanarak soruyu yanıtla.");

        return LlmRequest.of(LlmPurpose.MAIL_ANSWER, answerPrompt(), user.toString(), null,
                Map.of("question", question, "query", query, "count", sources.size()));
    }

    private String answerPrompt() {
        return """
                Relay'in posta asistanısın. Kullanıcının kendi gelen kutusunda yapılan bir aramanın
                sonuçlarını okuyup soruyu TÜRKÇE yanıtlıyorsun.
                Kurallar:
                - SADECE sana verilen maillere dayan. Listede olmayan hiçbir şeyi söyleme:
                  kargo numarası, tarih, tutar, gönderen uydurma.
                - Dayandığın her mail için köşeli parantezle kaynak ver: [1], [2]. Numaralar
                  yalnızca sana verilen listeden olabilir.
                - Sorunun cevabı maillerden çıkmıyorsa bunu açıkça söyle: "Bulduklarım bunu
                  söylemiyor" gibi. Tahmin yürütme.
                - En fazla 4 cümle. Madde işareti yok, başlık yok, JSON yok — düz metin.
                - Kullanıcıya doğrudan hitap et, kısa ve net ol.
                """;
    }

    /**
     * The answer's trust boundary: strip packaging, cap the length and delete citations that
     * point at a mail we never sent. A {@code [7]} next to three results is a fabricated source.
     */
    static String sanitizeAnswer(String raw, int sourceCount) {
        if (raw == null || raw.isBlank()) {
            return null;
        }
        String text = raw.trim();
        if (text.startsWith("```")) {
            int firstNewline = text.indexOf('\n');
            int lastFence = text.lastIndexOf("```");
            if (firstNewline > 0 && lastFence > firstNewline) {
                text = text.substring(firstNewline + 1, lastFence).trim();
            }
        }
        Matcher matcher = CITATION.matcher(text);
        StringBuilder sb = new StringBuilder();
        while (matcher.find()) {
            int index = Integer.parseInt(matcher.group(1));
            matcher.appendReplacement(sb, index >= 1 && index <= sourceCount
                    ? Matcher.quoteReplacement(matcher.group()) : "");
        }
        matcher.appendTail(sb);
        text = sb.toString().replaceAll("[ \\t]+", " ").replaceAll("\n{3,}", "\n\n").trim();
        if (text.isBlank()) {
            return null;
        }
        return text.length() > MAX_ANSWER_LENGTH
                ? text.substring(0, MAX_ANSWER_LENGTH).trim() + "…" : text;
    }

    // ---- wire -------------------------------------------------------------

    private static Map<String, Object> body(String question, MailQueryTranslator.Translation translation,
                                            String status, String answerSource, String answer,
                                            List<Source> sources, long tokens, double costUsd,
                                            String mode) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("question", question);
        map.put("query", translation.query());
        map.put("queryExplanation", translation.explanation());
        map.put("querySource", translation.source());
        map.put("status", status);
        map.put("answer", answer);
        map.put("answerSource", answerSource);
        List<Map<String, Object>> rows = new ArrayList<>();
        sources.forEach(source -> rows.add(source.view()));
        map.put("sources", rows);
        map.put("resultCount", rows.size());
        map.put("mode", mode);
        map.put("tokens", tokens);
        map.put("costUsd", costUsd);
        return map;
    }

    // ---- small helpers ----------------------------------------------------

    private static String snippet(List<JsonNode> messages, String id) {
        for (JsonNode message : messages) {
            if (id.equals(message.path("id").asText(""))) {
                String text = message.path("snippet").asText("").replaceAll("\\s+", " ").trim();
                return text.length() > MAX_SNIPPET_LENGTH
                        ? text.substring(0, MAX_SNIPPET_LENGTH) + "…" : text;
            }
        }
        return "";
    }

    /** {@code "Aras Kargo <bilgi@aras.com.tr>"} → {@code Aras Kargo}. */
    private static String person(String raw) {
        if (raw == null || raw.isBlank()) {
            return "";
        }
        int bracket = raw.indexOf('<');
        String name = bracket > 0 ? raw.substring(0, bracket) : raw;
        return name.trim().replaceAll("^\"|\"$", "");
    }

    /** {@code 2026-07-31T05:05:00Z} → {@code 2026-07-31}. */
    private static String day(String iso) {
        int t = iso == null ? -1 : iso.indexOf('T');
        return t > 0 ? iso.substring(0, t) : (iso == null ? "" : iso);
    }

    private static String blankTo(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }
}
