package com.relay.application.assistant;

import com.fasterxml.jackson.databind.JsonNode;
import com.relay.application.brief.BriefService;
import com.relay.application.port.ConnectionRepository;
import com.relay.application.port.LlmClient;
import com.relay.application.port.LlmPurpose;
import com.relay.application.port.LlmRequest;
import com.relay.application.port.LlmResponse;
import com.relay.application.port.Tool;
import com.relay.application.port.ToolRegistry;
import com.relay.application.port.ToolResult;
import com.relay.domain.Connection;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * {@code POST /api/ask} — "KAN-4 ne durumda?", "yarın toplantım var mı?", "kargolarım gelmiş
 * mi?" answered from the user's own accounts, with the receipts.
 *
 * <p>Three steps, and each one is visible in the response:
 * <ol>
 *   <li>{@link SourceRouter} decides <em>which registered READ tools</em> can answer and what
 *       to ask each one. The queries are returned to the caller, always — the user has to be
 *       able to see what was searched, and in which system.</li>
 *   <li>Those tools run in parallel. READ only: this endpoint has no path to a write tool,
 *       and it never starts a run.</li>
 *   <li>The model writes a Turkish answer <em>from those results only</em>, and the records it
 *       was given come back as {@code sources}, numbered across all providers.</li>
 * </ol>
 *
 * <p>The rule that matters: <b>no results means no answer</b>, and it is applied
 * <em>per source</em>. With an empty result set the model is never called at all — the
 * endpoint says it found nothing and repeats the queries it used. A confident paragraph
 * about a package that was never mentioned in any mail is the single worst thing an
 * assistant can do, and "Jira'da bulamadım ama mailde şu var" is the honest shape of a
 * partial answer.
 *
 * <p>A provider that is not connected is skipped rather than answered from demo fixtures —
 * but it is <em>named</em> in the answer ("Takvim bağlı değil"), because a silently missing
 * source looks exactly like a source with nothing in it.
 *
 * <p>The same applies when the model is on the stub: an assistant answer is only generated by
 * a real model. Degraded, the endpoint lists what it found and says so, which is true.
 */
public class AskService {

    private static final Logger LOG = System.getLogger(AskService.class.getName());

    /** Wire status for the caller: what kind of answer this is. */
    public static final String OK = "ok";
    public static final String EMPTY = "empty";
    public static final String UNAVAILABLE = "unavailable";
    public static final String ERROR = "error";

    /** How the {@code answer} text was produced — {@code llm} or a plain list of what was found. */
    public static final String ANSWER_LLM = "llm";
    public static final String ANSWER_LISTING = "listing";
    public static final String ANSWER_NONE = "none";

    private static final int MAX_QUESTION_LENGTH = 500;
    /** Asked of each provider; only the first few ever reach the model. */
    private static final int MAX_RESULTS = 10;
    private static final int MAX_SOURCES_PER_LOOKUP = 5;
    private static final int MAX_SOURCES = 10;
    private static final int MAX_ANSWER_LENGTH = 1200;
    private static final int MAX_SNIPPET_LENGTH = 220;

    private static final Pattern CITATION = Pattern.compile("\\[(\\d{1,2})]");

    private final ToolRegistry tools;
    private final ConnectionRepository connections;
    private final SourceRouter router;
    private final LlmClient llm;

    public AskService(ToolRegistry tools, ConnectionRepository connections,
                      SourceRouter router, LlmClient llm) {
        this.tools = tools;
        this.connections = connections;
        this.router = router;
        this.llm = llm;
    }

    /**
     * One record the answer is allowed to lean on — a mail, an issue, a pull request, an event.
     *
     * <p>{@code detail} never reaches the wire: it is the snippet or status the model reads,
     * and the wire shape is the five fields it always had plus {@code provider}, so a client
     * written against the mailbox-only version keeps rendering exactly what it rendered before.
     */
    public record Source(String id, String provider, String subject, String from, String at,
                         String url, String detail) {

        public Map<String, Object> view() {
            Map<String, Object> map = new LinkedHashMap<>();
            map.put("id", id);
            map.put("subject", subject);
            map.put("from", from);
            map.put("at", at);
            map.put("url", url);
            map.put("provider", provider);
            return map;
        }
    }

    /** One lookup, already run and already judged. {@code reason} is user-facing Turkish. */
    private record Found(String tool, String provider, String status, String reason,
                         String query, String explanation, List<Source> sources, String mode) {
    }

    // ---- entry point ------------------------------------------------------

    public Map<String, Object> ask(String question) {
        String cleaned = question == null ? "" : question.trim();
        if (cleaned.isEmpty()) {
            throw new IllegalArgumentException("soru boş olamaz");
        }
        if (cleaned.length() > MAX_QUESTION_LENGTH) {
            throw new IllegalArgumentException("soru çok uzun — en fazla "
                    + MAX_QUESTION_LENGTH + " karakter");
        }

        SourceRouter.Plan plan = router.route(cleaned);
        long tokens = plan.tokens();
        double cost = plan.costUsd();

        if (plan.lookups().isEmpty()) {
            return body(cleaned, plan, List.of(), UNAVAILABLE, ANSWER_NONE,
                    "Bu kurulumda soru sorabileceğim bir kaynak kayıtlı değil.",
                    List.of(), tokens, cost);
        }

        List<Found> found = run(plan.lookups());
        List<Source> sources = merge(found);
        String status = status(found, sources);

        if (sources.isEmpty()) {
            // Nothing found: state that, name the queries, and do not call the model.
            return body(cleaned, plan, found, status, ANSWER_NONE, nothingFound(found, status),
                    List.of(), tokens, cost);
        }

        String answer = null;
        String answerSource = ANSWER_LISTING;
        if (!llm.degraded()) {
            try {
                LlmResponse response = llm.complete(answerRequest(cleaned, found, sources));
                tokens += response.totalTokens();
                cost += response.costUsd();
                // The router can drop to the stub *inside* the call — the keys ran out
                // between the degraded() check and the request. Live, that put the stub's
                // "Sonuç bulunamadı: <the entire prompt>" on screen as the answer, internal
                // instructions and all. A stub response is not an answer, whatever the
                // client said about itself a moment earlier.
                answer = response.fallback() ? null : sanitizeAnswer(response.content(), sources.size());
                if (answer != null) {
                    answerSource = ANSWER_LLM;
                }
            } catch (RuntimeException e) {
                LOG.log(Level.WARNING, "ask: answer call failed ({0}) — listing the hits instead",
                        e.getClass().getSimpleName());
            }
        }
        if (answer == null) {
            answer = listing(sources);
        }
        return body(cleaned, plan, found, status, answerSource, withNotes(answer, found),
                sources, tokens, cost);
    }

    // ---- running the lookups ----------------------------------------------

    /**
     * Every routed tool at once, each on its own virtual thread — the same fan-out the daily
     * brief uses. A question costs the slowest provider, not their sum.
     */
    private List<Found> run(List<SourceRouter.Lookup> lookups) {
        if (lookups.size() == 1) {
            return List.of(run(lookups.get(0)));
        }
        List<Found> out = new ArrayList<>();
        try (ExecutorService pool = Executors.newVirtualThreadPerTaskExecutor()) {
            List<Future<Found>> futures = new ArrayList<>();
            for (SourceRouter.Lookup lookup : lookups) {
                futures.add(pool.submit(() -> run(lookup)));
            }
            for (int i = 0; i < futures.size(); i++) {
                SourceRouter.Lookup lookup = lookups.get(i);
                try {
                    out.add(futures.get(i).get());
                } catch (Exception e) {
                    LOG.log(Level.WARNING, "ask: " + lookup.tool() + " failed", e);
                    out.add(failed(lookup, providerLabel(lookup.tool()) + " çağrısı başarısız oldu."));
                }
            }
        }
        return out;
    }

    private Found run(SourceRouter.Lookup lookup) {
        String provider = providerLabel(lookup.tool());
        Tool tool = tools.find(lookup.tool()).orElse(null);
        if (tool == null) {
            return new Found(lookup.tool(), provider, UNAVAILABLE,
                    provider + " araması bu kurulumda kayıtlı değil.",
                    lookup.query(), lookup.explanation(), List.of(), null);
        }

        Connection connection = connections.findByProvider(tool.provider()).orElse(null);
        ToolResult result;
        try {
            result = tool.execute(SourceRouter.params(tool, lookup, MAX_RESULTS), connection);
        } catch (RuntimeException e) {
            LOG.log(Level.WARNING, "ask: {0} threw {1}", lookup.tool(), e.getClass().getSimpleName());
            return failed(lookup, provider + " çağrısı başarısız oldu.");
        }

        if (!result.ok()) {
            // The provider's own message can carry a token; it is translated, never forwarded.
            LOG.log(Level.WARNING, "ask: {0} failed: {1}", lookup.tool(), result.error());
            return new Found(lookup.tool(), provider, ERROR,
                    BriefService.failureReason(provider, result.error()),
                    lookup.query(), lookup.explanation(), List.of(), result.mode());
        }
        if ("replay (no connection)".equals(result.mode())) {
            // Live, without a connection: say so instead of passing demo fixtures off as
            // the user's own mailbox, board or calendar.
            return new Found(lookup.tool(), provider, UNAVAILABLE,
                    provider + " bağlı değil — Ayarlar'dan bağlayabilirsin.",
                    lookup.query(), lookup.explanation(), List.of(), result.mode());
        }
        return new Found(lookup.tool(), provider, OK, null, lookup.query(), lookup.explanation(),
                sources(lookup.tool(), provider, result.data()), result.mode());
    }

    private static Found failed(SourceRouter.Lookup lookup, String reason) {
        return new Found(lookup.tool(), providerLabel(lookup.tool()), ERROR, reason,
                lookup.query(), lookup.explanation(), List.of(), null);
    }

    private List<Source> merge(List<Found> found) {
        List<Source> out = new ArrayList<>();
        for (Found one : found) {
            for (Source source : one.sources()) {
                if (out.size() >= MAX_SOURCES) {
                    return out;
                }
                out.add(source);
            }
        }
        return out;
    }

    /**
     * One status for the whole question, from the per-source ones.
     *
     * <p>Anything found is {@code ok}. Nothing found but a source that ran is {@code empty} —
     * a true statement about the user's accounts. Only when no source ran at all does the
     * status describe the plumbing instead: {@code unavailable} before {@code error}, because
     * "connect it in Ayarlar" is something the user can act on.
     */
    private static String status(List<Found> found, List<Source> sources) {
        if (!sources.isEmpty()) {
            return OK;
        }
        boolean ran = false;
        boolean unavailable = false;
        for (Found one : found) {
            ran = ran || OK.equals(one.status());
            unavailable = unavailable || UNAVAILABLE.equals(one.status());
        }
        return ran ? EMPTY : unavailable ? UNAVAILABLE : ERROR;
    }

    // ---- results ----------------------------------------------------------

    /**
     * Provider payloads → the flat rows the answer may cite.
     *
     * <p>Field-driven rather than provider-driven on purpose: a mail has a {@code subject}, an
     * issue a {@code summary}, a pull request a {@code title}, an event a {@code title}, and
     * they all sit in the first array of objects the tool returned. A new READ tool that
     * answers in that shape shows up here with no change — which is the whole point of
     * routing to the registry instead of to a list of five known providers.
     */
    private List<Source> sources(String toolName, String provider, JsonNode data) {
        List<Source> out = new ArrayList<>();
        for (JsonNode row : rows(data)) {
            String id = identity(row);
            String title = text(row, TITLE_FIELDS);
            if (id.isBlank() && title.isBlank()) {
                continue; // not a record — a count, a query echo, a timezone
            }
            out.add(new Source(id.isBlank() ? title : id, provider,
                    blankTo(title, "(başlıksız)"), text(row, FROM_FIELDS), text(row, AT_FIELDS),
                    url(toolName, row, id), detail(row)));
            if (out.size() >= MAX_SOURCES_PER_LOOKUP) {
                break;
            }
        }
        return out;
    }

    /** The first array of objects in the payload, or the payload itself when it is one record. */
    private static List<JsonNode> rows(JsonNode data) {
        if (data == null || !data.isObject()) {
            return List.of();
        }
        Iterator<Map.Entry<String, JsonNode>> fields = data.fields();
        while (fields.hasNext()) {
            JsonNode value = fields.next().getValue();
            if (value.isArray() && !value.isEmpty() && value.get(0).isObject()) {
                List<JsonNode> out = new ArrayList<>();
                value.forEach(out::add);
                return out;
            }
        }
        return List.of(data);
    }

    private static final List<String> ID_FIELDS = List.of("issueKey", "key", "id", "number", "name");
    private static final List<String> TITLE_FIELDS = List.of("subject", "title", "summary", "name");
    private static final List<String> FROM_FIELDS =
            List.of("from", "author", "assignee", "organizer", "attendees", "user");
    private static final List<String> AT_FIELDS =
            List.of("receivedAt", "updatedAt", "updated", "start", "createdAt", "created", "at", "date");
    private static final List<String> URL_FIELDS = List.of("url", "html_url", "htmlLink", "link");
    private static final List<String> DETAIL_FIELDS =
            List.of("snippet", "status", "state", "location", "reason", "description");

    /** {@code acme/payments#128} beats {@code 128}: a number alone identifies nothing. */
    private static String identity(JsonNode row) {
        String repo = row.path("repo").asText("");
        if (!repo.isBlank() && row.has("number")) {
            return repo + "#" + row.path("number").asText("");
        }
        return text(row, ID_FIELDS);
    }

    private static String text(JsonNode row, List<String> names) {
        for (String name : names) {
            JsonNode value = row.get(name);
            if (value == null || value.isNull()) {
                value = row.path("fields").get(name);
            }
            String read = value == null ? "" : value(value);
            if (!read.isBlank()) {
                return read;
            }
        }
        return "";
    }

    /** Jira wraps a person in {@code {displayName}}, calendar an attendee list in an array. */
    private static String value(JsonNode node) {
        if (node.isObject()) {
            for (String field : List.of("displayName", "name", "email", "text", "summary")) {
                String read = node.path(field).asText("");
                if (!read.isBlank()) {
                    return read;
                }
            }
            return "";
        }
        if (node.isArray()) {
            return node.isEmpty() ? "" : value(node.get(0));
        }
        return node.asText("").trim();
    }

    private static String detail(JsonNode row) {
        String text = text(row, DETAIL_FIELDS).replaceAll("\\s+", " ").trim();
        return text.length() > MAX_SNIPPET_LENGTH ? text.substring(0, MAX_SNIPPET_LENGTH) + "…" : text;
    }

    /** A deep link the user can click. Gmail and Jira do not ship one; they are built. */
    private String url(String toolName, JsonNode row, String id) {
        String url = text(row, URL_FIELDS);
        if (!url.isBlank()) {
            return url;
        }
        if (toolName.startsWith("gmail.") && !id.isBlank()) {
            return "https://mail.google.com/mail/u/0/#all/" + id;
        }
        if (toolName.startsWith("jira.") && !id.isBlank()) {
            String base = connections.findByProvider("jira")
                    .map(connection -> connection.getOrDefault("baseUrl", ""))
                    .orElse("").trim();
            if (base.endsWith("/")) {
                base = base.substring(0, base.length() - 1);
            }
            return base.isBlank() ? "" : base + "/browse/" + id;
        }
        return "";
    }

    // ---- what the endpoint says -------------------------------------------

    /** What the endpoint says when no model may speak: the hits, in order, and nothing else. */
    private static String listing(List<Source> sources) {
        StringBuilder sb = new StringBuilder();
        sb.append(sources.size()).append(" kayıt buldum:");
        for (int i = 0; i < sources.size(); i++) {
            Source source = sources.get(i);
            sb.append("\n[").append(i + 1).append("] ").append(source.provider())
                    .append(" · ").append(source.subject());
            String from = person(source.from());
            if (!from.isBlank()) {
                sb.append(" — ").append(from);
            }
            String day = day(source.at());
            if (!day.isBlank()) {
                sb.append(" (").append(day).append(')');
            }
        }
        return sb.toString();
    }

    /** No results anywhere: name every query that was run, and every source that could not be. */
    private static String nothingFound(List<Found> found, String status) {
        List<String> ran = new ArrayList<>();
        for (Found one : found) {
            if (OK.equals(one.status())) {
                ran.add(one.provider() + (one.query().isBlank() ? "" : " — " + one.query()));
            }
        }
        StringBuilder sb = new StringBuilder();
        if (!ran.isEmpty()) {
            sb.append(ran.size() == 1 ? "Bu sorguyla eşleşen bir şey bulamadım: "
                            : "Bu sorgularla eşleşen bir şey bulamadım: ")
                    .append(String.join("; ", ran)).append('.');
        }
        String notes = notes(found);
        if (!notes.isBlank()) {
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append(notes);
            if (ran.isEmpty()) {
                // Nothing ran at all: the query is still the receipt for what was attempted.
                String attempted = found.isEmpty() ? "" : found.get(0).query();
                if (!attempted.isBlank()) {
                    sb.append(" Sorguyu şöyle çevirmiştim: ").append(attempted);
                }
            }
        }
        if (sb.length() == 0) {
            sb.append("Sorunun cevabını bulamadım.");
        }
        if (EMPTY.equals(status)) {
            sb.append(" Sorunu biraz farklı sorarsan tekrar deneyebilirim.");
        }
        return sb.toString();
    }

    /** A provider that was skipped is named — a silent gap reads as "there is nothing there". */
    private static String notes(List<Found> found) {
        List<String> out = new ArrayList<>();
        for (Found one : found) {
            if (!OK.equals(one.status()) && one.reason() != null && !out.contains(one.reason())) {
                out.add(one.reason());
            }
        }
        return String.join(" ", out);
    }

    private static String withNotes(String answer, List<Found> found) {
        StringBuilder notes = new StringBuilder(notes(found));
        String silent = silent(found);
        if (!silent.isBlank()) {
            if (notes.length() > 0) {
                notes.append(' ');
            }
            notes.append(silent);
        }
        return notes.length() == 0 ? answer : answer + "\n\n" + notes;
    }

    /**
     * A source that answered with nothing, named next to the ones that answered with
     * something.
     *
     * <p>Live, "jira'da bende ne var ve PR'larım ne durumda" listed one pull request and said
     * nothing at all about Jira, which had come back empty. Read as an answer, that is a
     * claim about GitHub and silence about the board — and silence is where the reader puts
     * their own assumption. "Jira'da bulamadım ama şunu buldum" is the honest shape.
     */
    private static String silent(List<Found> found) {
        List<String> quiet = new ArrayList<>();
        for (Found one : found) {
            if (OK.equals(one.status()) && one.sources().isEmpty() && !quiet.contains(one.provider())) {
                quiet.add(one.provider());
            }
        }
        if (quiet.isEmpty()) {
            return "";
        }
        // Turkish suffixes differ per provider name (Jira'da, Gmail'de, GitHub'da), so the
        // names are listed after a colon rather than inflected into a sentence.
        return (quiet.size() == 1 ? "Bu kaynakta eşleşen bir şey yok: " : "Bu kaynaklarda eşleşen bir şey yok: ")
                + String.join(", ", quiet) + ".";
    }

    // ---- answer -----------------------------------------------------------

    private LlmRequest answerRequest(String question, List<Found> found, List<Source> sources) {
        StringBuilder user = new StringBuilder();
        user.append("SORU: ").append(question).append('\n');
        user.append("ÇALIŞTIRILAN ARAMALAR:\n");
        for (Found one : found) {
            if (OK.equals(one.status())) {
                user.append("- ").append(one.provider())
                        .append(one.query().isBlank() ? "" : ": " + one.query()).append('\n');
            }
        }
        user.append("\nBULUNAN KAYITLAR:\n");
        for (int i = 0; i < sources.size(); i++) {
            Source source = sources.get(i);
            user.append('[').append(i + 1).append("] kaynak=").append(source.provider())
                    .append(" | kim=").append(source.from())
                    .append(" | başlık=").append(source.subject())
                    .append(" | tarih=").append(source.at())
                    .append(" | ayrıntı=").append(source.detail())
                    .append('\n');
        }
        user.append("\nBu kayıtlara dayanarak soruyu yanıtla.");

        return LlmRequest.of(LlmPurpose.ASK_ANSWER, answerPrompt(), user.toString(), null,
                Map.of("question", question, "count", sources.size()));
    }

    private String answerPrompt() {
        return """
                Relay'in asistanısın. Kullanıcının kendi hesaplarında (posta kutusu, Jira, GitHub,
                takvim) yapılan aramaların sonuçlarını okuyup soruyu TÜRKÇE yanıtlıyorsun.
                Kurallar:
                - SADECE sana verilen kayıtlara dayan. Listede olmayan hiçbir şeyi söyleme:
                  kargo numarası, tarih, tutar, durum, kişi uydurma.
                - Dayandığın her kayıt için köşeli parantezle kaynak ver: [1], [2]. Numaralar
                  yalnızca sana verilen listeden olabilir.
                - Birden fazla kaynaktan kayıt geldiyse hangisinin nereden geldiğini söyle
                  ("Jira'da…", "Mailde…").
                - Sorunun cevabı kayıtlardan çıkmıyorsa bunu açıkça söyle: "Bulduklarım bunu
                  söylemiyor" gibi. Tahmin yürütme.
                - En fazla 4 cümle. Madde işareti yok, başlık yok, JSON yok — düz metin.
                - Kullanıcıya doğrudan hitap et, kısa ve net ol.
                """;
    }

    /**
     * The answer's trust boundary: strip packaging, cap the length and delete citations that
     * point at a record we never sent. A {@code [7]} next to three results is a fabricated source.
     */
    static String sanitizeAnswer(String raw, int sourceCount) {
        if (raw == null || raw.isBlank()) {
            return null;
        }
        String text = raw.trim();
        if (text.startsWith("```")) {
            int firstNewline = text.indexOf('\n');
            int lastFence = text.lastIndexOf("```");
            if (firstNewline > 0 && lastFence > firstNewline) {
                text = text.substring(firstNewline + 1, lastFence).trim();
            }
        }
        Matcher matcher = CITATION.matcher(text);
        StringBuilder sb = new StringBuilder();
        while (matcher.find()) {
            int index = Integer.parseInt(matcher.group(1));
            matcher.appendReplacement(sb, index >= 1 && index <= sourceCount
                    ? Matcher.quoteReplacement(matcher.group()) : "");
        }
        matcher.appendTail(sb);
        text = sb.toString().replaceAll("[ \\t]+", " ").replaceAll("\n{3,}", "\n\n").trim();
        if (text.isBlank()) {
            return null;
        }
        return text.length() > MAX_ANSWER_LENGTH
                ? text.substring(0, MAX_ANSWER_LENGTH).trim() + "…" : text;
    }

    // ---- wire -------------------------------------------------------------

    /**
     * The response body. The mailbox-era fields are unchanged and mean what they meant:
     * {@code query} is the query that produced the answer, {@code mode} how that call was
     * served. {@code sources[]} is additive per record ({@code provider}) and
     * {@code sourceBreakdown} is additive per lookup, so a client that knows neither renders
     * what it always rendered.
     */
    private static Map<String, Object> body(String question, SourceRouter.Plan plan,
                                            List<Found> found, String status, String answerSource,
                                            String answer, List<Source> sources,
                                            long tokens, double costUsd) {
        Found primary = primary(found);

        Map<String, Object> map = new LinkedHashMap<>();
        map.put("question", question);
        map.put("query", primary == null ? "" : primary.query());
        map.put("queryExplanation", primary == null
                ? "Soruyu sorabileceğim bir kaynak bulamadım." : primary.explanation());
        map.put("querySource", plan.source());
        map.put("status", status);
        map.put("answer", answer);
        map.put("answerSource", answerSource);
        List<Map<String, Object>> rows = new ArrayList<>();
        sources.forEach(source -> rows.add(source.view()));
        map.put("sources", rows);
        map.put("resultCount", rows.size());
        map.put("mode", primary == null ? null : primary.mode());
        map.put("tokens", tokens);
        map.put("costUsd", costUsd);
        map.put("sourceBreakdown", breakdown(found));
        return map;
    }

    /** The lookup the top-level {@code query} describes: whichever one actually answered. */
    private static Found primary(List<Found> found) {
        for (Found one : found) {
            if (OK.equals(one.status()) && !one.sources().isEmpty()) {
                return one;
            }
        }
        return found.isEmpty() ? null : found.get(0);
    }

    /** Per-source detail, additive: which tool ran, with what, and what came back. */
    private static List<Map<String, Object>> breakdown(List<Found> found) {
        List<Map<String, Object>> out = new ArrayList<>();
        for (Found one : found) {
            Map<String, Object> row = new LinkedHashMap<>();
            row.put("tool", one.tool());
            row.put("provider", one.provider());
            row.put("status", one.status());
            row.put("query", one.query());
            row.put("queryExplanation", one.explanation());
            row.put("reason", one.reason());
            row.put("resultCount", one.sources().size());
            row.put("mode", one.mode());
            out.add(row);
        }
        return out;
    }

    // ---- small helpers ----------------------------------------------------

    /** The provider as the user names it, from the tool name — {@code calendar.*} is "Takvim". */
    static String providerLabel(String toolName) {
        int dot = toolName == null ? -1 : toolName.indexOf('.');
        String provider = dot > 0 ? toolName.substring(0, dot) : (toolName == null ? "" : toolName);
        return switch (provider) {
            case "gmail" -> "Gmail";
            case "calendar" -> "Takvim";
            case "github" -> "GitHub";
            case "jira" -> "Jira";
            case "slack" -> "Slack";
            default -> provider.isBlank() ? "Kaynak" : provider;
        };
    }

    /** {@code "Aras Kargo <bilgi@aras.com.tr>"} → {@code Aras Kargo}. */
    private static String person(String raw) {
        if (raw == null || raw.isBlank()) {
            return "";
        }
        int bracket = raw.indexOf('<');
        String name = bracket > 0 ? raw.substring(0, bracket) : raw;
        return name.trim().replaceAll("^\"|\"$", "");
    }

    /** {@code 2026-07-31T05:05:00Z} → {@code 2026-07-31}. */
    private static String day(String iso) {
        int t = iso == null ? -1 : iso.indexOf('T');
        return t > 0 ? iso.substring(0, t) : (iso == null ? "" : iso);
    }

    private static String blankTo(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }
}
